/* -*- c++ -*- */
/*
 * Gqrx SDR: Software defined radio receiver powered by GNU Radio and Qt
 *           https://gqrx.dk/
 *
 * Copyright 2023 vladisslav2011@gmail.com.
 *
 * Gqrx is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * Gqrx is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gqrx; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#include <QDir>
#include "dcontrols.h"

static const std::array<c_def,C_COUNT> store{

c_def()
    .idx(C_TEST)
    .name("test")
    .title("test ctl")
    .title_placement(c_def::grid_placement(PLACE_SAME,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("widget test value")
//    .g_type(G_TOGGLEBUTTON)
//    .g_type(G_SLIDER)
//    .g_type(G_SPINBOX)
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RDS)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .v4_config_group("test")
    .config_key("test")
//    .tab("Tab0")
    .bookmarks_column(-1)
    .bookmarks_key("-1")
    .v_type(V_INT)
    .def(0)
    .min(0)
    .max(1000)
    .step(10)
    .frac_digits(1)
    .readable(true)
    .writable(true)
    .event(false)
    .presets(
    {
    })
    ,
    

c_def()
    .idx(C_AUDIO_FFT_SPLIT)
    .name("audio_fft_split")
    .title("Panadapter")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .next_title("Waterfall")
    .next_placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Audio FFT split")
    .tab("FFT")
    .g_type(G_SLIDER)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("fft_split")
    .v_type(V_INT)
    .def(100)
    .min(0)
    .max(100)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_FFT_PAND_MIN_DB)
    .name("audio_fft_pand_min_db")
    .title("Panadapter dB range")
    .hint("Set pandapter dB range")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NONE,PLACE_NONE))
    .tab("FFT")
    .g_type(G_RANGESLIDER)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("pandapter_min_db")
    .v_type(V_INT)
    .def(-80)
    .min(-200)
    .max(0)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_FFT_PAND_MAX_DB)
    .base(C_AUDIO_FFT_PAND_MIN_DB)
    .name("audio_fft_pand_max_db")
    .title("Panadapter dB range")
    .hint("Set pandapter dB range")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("FFT")
    .g_type(G_RANGESLIDER)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("pandapter_max_db")
    .v_type(V_INT)
    .def(0)
    .min(-200)
    .max(0)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_FFT_WF_MIN_DB)
    .name("audio_fft_wf_min_db")
    .title("Waterfall dB range")
    .hint("Set waterfall dB range")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NONE,PLACE_NONE))
    .tab("FFT")
    .g_type(G_RANGESLIDER)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("waterfall_min_db")
    .v_type(V_INT)
    .def(-80)
    .min(-200)
    .max(0)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_FFT_WF_MAX_DB)
    .base(C_AUDIO_FFT_WF_MIN_DB)
    .name("audio_fft_wf_max_db")
    .title("Waterfall dB range")
    .hint("Set waterfall dB range")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("FFT")
    .g_type(G_RANGESLIDER)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("waterfall_max_db")
    .v_type(V_INT)
    .def(0)
    .min(-200)
    .max(0)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_FFT_RANGE_LOCKED)
    .name("Lock")
    .title("")
    .hint("Lock panadapter and waterfall sliders together")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("FFT")
    .g_type(G_TOGGLEBUTTON)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v3_config_group("audio")
    .config_key("db_ranges_locked")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_REC_DIR)
    .name("rec_location")
    .title("Location for recorded audio files:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0,1,3,ALIGN_LEFT))
    .placement(c_def::grid_placement(PLACE_NEXT,0,1,2))
    .tab("Recording")
    .g_type(G_TEXT)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("rec_dir")
    .bookmarks_column(27)
    .bookmarks_key("REC DIR")
    .v_type(V_STRING)
    .def(QDir::homePath().toStdString())
    .min("")
    .max("")
    .step("")
    ,
c_def()
    .idx(C_AUDIO_REC_DIR_BTN)
    .name("Select")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,SIZE_PREFERRED))
    .tab("Recording")
    .g_type(G_BUTTON)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v_type(V_INT)
    .def(1)
    .min(0)
    .max(1)
    .step(1)
    .readable(0)
    ,
c_def()
    .idx(C_AUDIO_REC_SQUELCH_TRIGGERED)
    .name("Squelch triggered")
    .title("")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,2))
    .hint("Enable squelch triggered recording")
    .tab("Recording")
    .g_type(G_CHECKBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("squelch_triggered_recording")
    .bookmarks_column(28)
    .bookmarks_key("REC SQL Trig")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_REC_MIN_TIME)
    .name("Min time")
    .title("Min time")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,2))
    .hint("Minimum squelch triggered recording fragment time")
    .tab("Recording")
    .g_type(G_SPINBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("rec_min_time")
    .bookmarks_column(29)
    .bookmarks_key("REC Min Time")
    .v_type(V_INT)
    .suffix("ms")
    .def(0)
    .min(0)
    .max(10000)
    .step(100)
    ,
c_def()
    .idx(C_AUDIO_REC_MAX_GAP)
    .name("Max gap")
    .title("Max gap")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,2))
    .hint("Maximum squelch triggered recording silence time")
    .tab("Recording")
    .g_type(G_SPINBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("rec_max_gap")
    .bookmarks_column(30)
    .bookmarks_key("REC Max Gap")
    .v_type(V_INT)
    .suffix("ms")
    .def(0)
    .min(0)
    .max(10000)
    .step(100)
    ,
c_def()
    .idx(C_AUDIO_REC_COPY)
    .name("All VFOs")
    .title("Copy to")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("Recording")
    .g_type(G_BUTTON)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_GUI)
    .v_type(V_INT)
    .def(1)
    .min(0)
    .max(1)
    .step(1)
    .readable(0)
    ,
c_def()
    .idx(C_AUDIO_UDP_HOST)
    .name("udp_host")
    .title("UDP host")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("Network")
    .g_type(G_TEXT)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("udp_host")
    .v_type(V_STRING)
    .def("127.0.0.1")
    .min("")
    .max("")
    .step("")
    ,
c_def()
    .idx(C_AUDIO_UDP_PORT)
    .name("udp_port")
    .title("UDP port")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .tab("Network")
    .g_type(G_SPINBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("udp_port")
    .v_type(V_INT)
    .def(7355)
    .min(1)
    .max(65535)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_UDP_STEREO)
    .name("UDP stereo")
    .title("")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .tab("Network")
    .g_type(G_CHECKBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("udp_stereo")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AUDIO_DEDICATED_DEV)
    .name("dev")
    .title("Device")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,SIZE_PREFERRED))
    .tab("Audio")
    .g_type(G_COMBO)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("")
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    ,
c_def()
    .idx(C_AUDIO_DEDICATED_ON)
    .name("enable dedicated")
    .title("")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .tab("Audio")
    .g_type(G_CHECKBOX)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    .event(1)
    ,
c_def()
    .idx(C_AUDIO_DEDICATED_ERROR)
    .name("Error")
    .title("Error")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,0))
    .hint("Error mesage")
    .tab("Audio")
    .g_type(G_LABEL)
    .dock(D_AUDIO)
    .window(W_CHILD)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,

c_def()
    .idx(C_AGC_MAN_GAIN)
    .name("Gain:")
    .title("Gain:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,5))
    .hint("Gain:")
    .g_type(G_SLIDER)
    .dock(D_AUDIO)
    .scope(S_VFO)
    .v3_config_group("audio")
    .config_key("gain")
    .bookmarks_column(10)
    .bookmarks_key("AGC Manual Gain")
    .v_type(V_DOUBLE)
    .frac_digits(1)
    .def(-6.0)
    .min(-100.0)
    .max(100.0)
    .step(0.1)
    .event(true)
    .presets({
        {"0","0 db",0.0},
        {"-6","-6 db",-6.0},
    })
    ,
c_def()
    .idx(C_AGC_MAN_GAIN_LABEL)
    .name("Gain:")
    .title("Gain:")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Gain value")
    .next_title(" db")
    .next_placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .g_type(G_LABEL)
    .dock(D_AUDIO)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_MAX_GAIN)
    .name("Max Gain")
    .title("Max Gain")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Max Gain")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_maxgain")
    .bookmarks_column(11)
    .bookmarks_key("AGC Max Gain")
    .v_type(V_INT)
    .def(100)
    .min(0)
    .max(150)
    .step(1)
    ,
c_def()
    .idx(C_AGC_MAX_GAIN_LABEL)
    .name("Max gain")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Max gain")
    .suffix(" db")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_TARGET)
    .name("Target")
    .title("Target")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Target")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_target_level")
    .bookmarks_column(9)
    .bookmarks_key("AGC Target Level")
    .v_type(V_INT)
    .def(0)
    .min(-100)
    .max(0)
    .step(1)
    ,
c_def()
    .idx(C_AGC_TARGET_LABEL)
    .name("Target level")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Target level")
    .suffix(" db")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_ATTACK)
    .name("Attack")
    .title("Attack")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Attack")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_attack")
    .bookmarks_column(12)
    .bookmarks_key("AGC Attack")
    .v_type(V_INT)
    .def(20)
    .min(20)
    .max(1000)
    .step(10)
    ,
c_def()
    .idx(C_AGC_ATTACK_LABEL)
    .name("Attack value")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Attack value")
    .suffix(" ms")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_DECAY)
    .name("Decay")
    .title("Decay")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Decay")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_decay")
    .bookmarks_column(13)
    .bookmarks_key("AGC Decay")
    .v_type(V_INT)
    .def(500)
    .min(50)
    .max(5000)
    .step(10)
    ,
c_def()
    .idx(C_AGC_DECAY_LABEL)
    .name("Decay value")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Decay value")
    .suffix(" ms")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_HANG)
    .name("Hang")
    .title("Hang")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Hang")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_hang")
    .bookmarks_column(14)
    .bookmarks_key("AGC Hang")
    .v_type(V_INT)
    .def(0)
    .min(0)
    .max(5000)
    .step(10)
    ,
c_def()
    .idx(C_AGC_HANG_LABEL)
    .name("Hang value")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Hang value")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .suffix(" ms")
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_PANNING)
    .name("Panning")
    .title("Panning")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("Panning")
    .g_type(G_SLIDER)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_panning")
    .bookmarks_column(15)
    .bookmarks_key("Panning")
    .v_type(V_INT)
    .def(0)
    .min(-100)
    .max(100)
    .step(1)
    .event(true)
    .presets({
        {"Center","Center",0}
    })
    ,
c_def()
    .idx(C_AGC_PANNING_LABEL)
    .name("Panning value")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT,1,1,ALIGN_RIGHT))
    .hint("Panning value")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_AGC_PANNING_AUTO)
    .name("Auto panning")
    .title("Auto panning")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .hint("Auto panning")
    .g_type(G_CHECKBOX)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_panning_auto")
    .bookmarks_column(16)
    .bookmarks_key("Auto Panning")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AGC_ON)
    .name("AGC On")
    .title("AGC On")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("AGC On")
    .g_type(G_NONE)
    .dock(D_RXOPT)
    .window(W_AGC_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("agc_on")
    .bookmarks_column(8)
    .bookmarks_key("AGC On")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,

c_def()
    .idx(C_NB1_THR)
    .name("NB1 threshold")
    .title("NB1 threshold")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NB1 threshold")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_NB_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("nb1thr")
    .bookmarks_column(24)
    .bookmarks_key("NB1 Threshold")
    .v_type(V_DOUBLE)
    .frac_digits(1)
    .def(2.0)
    .min(1.0)
    .max(20.0)
    .step(0.1)
    ,
c_def()
    .idx(C_NB2_THR)
    .name("NB2 threshold")
    .title("NB2 threshold")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NB2 threshold")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_NB_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("nb2thr")
    .bookmarks_column(26)
    .bookmarks_key("NB2 Threshold")
    .v_type(V_DOUBLE)
    .frac_digits(1)
    .def(2.0)
    .min(0.0)
    .max(15.0)
    .step(0.1)
    ,
c_def()
    .idx(C_NB3_GAIN)
    .name("NB3 gain")
    .title("NB3 gain")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NB3 gain")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_NB_OPT)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("nb3gain")
    .bookmarks_column(-1)
    .bookmarks_key("")
    .v_type(V_DOUBLE)
    .frac_digits(1)
    .def(5.0)
    .min(0.0)
    .max(10.0)
    .step(0.1)
    ,

c_def()
    .idx(C_NFM_MAXDEV)
    .name("Max dev")
    .title("Max dev")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NFM Max dev")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFM)
    .v3_config_group("receiver")
    .config_key("fm_maxdev")
    .bookmarks_column(18)
    .bookmarks_key("FM Max Deviation")
    .v_type(V_DOUBLE)
    .frac_digits(0)
    .def(5000.0)
    .min(10.0)
    .max(75000.0)
    .step(10.0)
    .presets(
    {
        {"0","Voice (2.5 kHz)",2500.0},
        {"1","Voice (5 kHz)",5000.0},
        {"2","APT (17 kHz)",17000.0},
        {"3","APT (25 kHz)",25000.0},
    })
    ,
c_def()
    .idx(C_NFMPLL_MAXDEV)
    .name("Max dev")
    .title("Max dev")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NFM Max dev")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFMPLL)
    .v3_config_group("receiver")
    .config_key("")
    .bookmarks_column(-1)
    .bookmarks_key("")
    .v_type(V_DOUBLE)
    .frac_digits(0)
    .def(2500.0)
    .min(10.0)
    .max(75000.0)
    .step(10.0)
    .presets(
    {
        {"0","Voice (2.5 kHz)",2500.0},
        {"1","Voice (5 kHz)",5000.0},
        {"2","APT (17 kHz)",17000.0},
        {"3","APT (25 kHz)",25000.0},
    })
    ,
c_def()
    .idx(C_NFM_DEEMPH)
    .name("Deemphasis")
    .title("Deemphasis")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NFM Deemphasis")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFM)
    .v3_config_group("receiver")
    .config_key("fm_deemph")
    .bookmarks_column(19)
    .bookmarks_key("FM Deemphasis")
    .v_type(V_DOUBLE)
    .def(75.0)
    .min(0.0)
    .max(1000.0)
    .step(1.0)
    .presets(
    {
        {"0","Off",0.0},
        {"1","25 us",25.0},
        {"2","50 us",50.0},
        {"3","75 us",75.0},
        {"4","100 us",100.0},
        {"5","250 us",250.0},
        {"6","530 us",530.0},
        {"7","1 ms",1000.0},
    })
    ,
c_def()
    .idx(C_NFM_SUBTONE_FILTER)
    .name("Subtone filter")
    .title("Subtone filter")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .hint("NFM Subtone filter")
    .g_type(G_CHECKBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFM)
    .v3_config_group("receiver")
    .config_key("")
    .bookmarks_column(-1)
    .bookmarks_key("")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_NFMPLL_DAMPING_FACTOR)
    .name("Damping factor")
    .title("Damping factor")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NFM PLL Damping factor")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFMPLL)
    .v3_config_group("receiver")
    .config_key("fmpll_damping_factor")
    .bookmarks_column(-1)
    .bookmarks_key("")
    .v_type(V_DOUBLE)
    .frac_digits(2)
    .def(0.7)
    .min(0.01)
    .max(1.0)
    .step(0.01)
    ,
c_def()
    .idx(C_NFMPLL_PLLBW)
    .name("PLL")
    .title("PLL")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("NFM PLL bandwidth")
    .g_type(G_DOUBLESPINBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFMPLL)
    .v3_config_group("receiver")
    .config_key("nfmpll_bw")
    .bookmarks_column(31)
    .bookmarks_key("NFM PLL BW")
    .v_type(V_DOUBLE)
    .frac_digits(4)
    .def(0.027)
    .min(0.0001)
    .max(0.5)
    .step(0.001)
    ,
c_def()
    .idx(C_NFMPLL_SUBTONE_FILTER)
    .name("Subtone filter")
    .title("Subtone filter")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .hint("NFM PLL Subtone filter")
    .g_type(G_CHECKBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_NFMPLL)
    .v3_config_group("receiver")
    .config_key("subtone_filter")
    .bookmarks_column(-1)
    .bookmarks_key("")
    .v_type(V_BOOLEAN)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AMSYNC_PLLBW)
    .name("PLL")
    .title("PLL")
    .title_placement(c_def::grid_placement(0,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("AM SYNC PLL bandwidth")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_AM_SYNC)
    .v3_config_group("receiver")
    .config_key("pll_bw")
    .bookmarks_column(22)
    .bookmarks_key("PLL BW")
    .v_type(V_DOUBLE)
    .frac_digits(4)
    .def(0.001)
    .min(0.0001)
    .max(0.01)
    .step(0.0001)
    .presets(
    {
        {"Fast","Fast",0.01},
        {"Medium","Medium",0.001},
        {"Slow","Slow",0.0001},
    })
    ,
c_def()
    .idx(C_AMSYNC_DCR)
    .name("DCR")
    .title("DCR")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .hint("AM SYNC DC remove filter")
    .g_type(G_CHECKBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_AM_SYNC)
    .v3_config_group("receiver")
    .config_key("amsync_dcr")
    .bookmarks_column(21)
    .bookmarks_key("AM SYNC DCR")
    .v_type(V_BOOLEAN)
    .def(1)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_AM_DCR)
    .name("DCR")
    .title("DCR")
    .title_placement(c_def::grid_placement(PLACE_NONE,0))
    .placement(c_def::grid_placement(PLACE_NEXT,1))
    .hint("AM DC remove filter")
    .g_type(G_CHECKBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_AM)
    .v3_config_group("receiver")
    .config_key("am_dcr")
    .bookmarks_column(20)
    .bookmarks_key("AM DCR")
    .v_type(V_BOOLEAN)
    .def(1)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_CW_OFFSET)
    .name("CW offset")
    .title("CW offset")
    .title_placement(c_def::grid_placement(0,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("CW offset, Hz")
    .g_type(G_SPINBOX)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_CW)
    .v3_config_group("receiver")
    .config_key("cwoffset")
    .bookmarks_column(17)
    .bookmarks_key("CW Offset")
    .v_type(V_INT)
    .def(700)
    .min(0)
    .max(2000)
    .step(1)
    ,
c_def()
    .idx(C_DEMOD_OFF_DUMMY)
    .name("No options for this demod")
    .title("No options for this demod")
    .title_placement(c_def::grid_placement(PLACE_SAME,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("No options for this demod")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_OFF)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    ,
c_def()
    .idx(C_RAWIQ_DUMMY)
    .name("No options for this demod")
    .title("No options for this demod")
    .title_placement(c_def::grid_placement(PLACE_SAME,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("No options for this demod")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_RAW)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    ,
c_def()
    .idx(C_SSB_DUMMY)
    .name("No options for this demod")
    .title("No options for this demod")
    .title_placement(c_def::grid_placement(PLACE_SAME,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("No options for this demod")
    .g_type(G_LABEL)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .v_type(V_STRING)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_SSB)
    .def("")
    .min("")
    .max("")
    .step("")
    .writable(false)
    ,
c_def()
    .idx(C_WFM_DEEMPH)
    .name("Deemphasis")
    .title("Deemphasis")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("WFM Deemphasis")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_WFM_MONO)
    .v3_config_group("receiver")
    .config_key("wfm_deemph")
    .v_type(V_DOUBLE)
    .def(50.0)
    .min(0.0)
    .max(1000.0)
    .step(1.0)
    .presets(
    {
        {"0","Off",0.0},
        {"1","25 us",25.0},
        {"2","50 us",50.0},
        {"3","75 us",75.0},
        {"4","100 us",100.0},
        {"5","250 us",250.0},
        {"6","530 us",530.0},
        {"7","1 ms",1000.0},
    })
    ,
c_def()
    .idx(C_WFM_STEREO_DEEMPH)
    .name("Deemphasis")
    .title("Deemphasis")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("WFM Deemphasis")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_WFM_STEREO)
    .v3_config_group("receiver")
    .config_key("wfm_deemph")
    .v_type(V_DOUBLE)
    .def(50.0)
    .min(0.0)
    .max(1000.0)
    .step(1.0)
    .presets(
    {
        {"0","Off",0.0},
        {"1","25 us",25.0},
        {"2","50 us",50.0},
        {"3","75 us",75.0},
        {"4","100 us",100.0},
        {"5","250 us",250.0},
        {"6","530 us",530.0},
        {"7","1 ms",1000.0},
    })
    ,
c_def()
    .idx(C_WFM_OIRT_DEEMPH)
    .name("Deemphasis")
    .title("Deemphasis")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("WFM Deemphasis")
    .g_type(G_COMBO)
    .dock(D_RXOPT)
    .window(W_DEMOD_OPT)
    .scope(S_VFO)
    .demod_specific(true)
    .demodgroup(Modulations::GRP_WFM_STEREO_OIRT)
    .v3_config_group("receiver")
    .config_key("wfm_deemph")
    .v_type(V_DOUBLE)
    .def(50.0)
    .min(0.0)
    .max(1000.0)
    .step(1.0)
    .presets(
    {
        {"0","Off",0.0},
        {"1","25 us",25.0},
        {"2","50 us",50.0},
        {"3","75 us",75.0},
        {"4","100 us",100.0},
        {"5","250 us",250.0},
        {"6","530 us",530.0},
        {"7","1 ms",1000.0},
    })
    ,

c_def()
    .idx(C_RDS_ON)
    .name("Enable RDS")
    .title("Enable RDS")
    .title_placement(c_def::grid_placement(PLACE_NONE,PLACE_NONE))
    .placement(c_def::grid_placement(PLACE_NEXT,0,1,2))
    .hint("Enable RDS decoder")
    .g_type(G_CHECKBOX)
    .dock(D_RDS)
    .scope(S_VFO)
    .v3_config_group("receiver")
    .config_key("rds")
    .v_type(V_INT)
    .def(0)
    .min(0)
    .max(1)
    .step(1)
    ,
c_def()
    .idx(C_RDS_PS)
    .name("Station name")
    .title("Station Name:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Station name")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_PTY)
    .name("Program type")
    .title("Program Type:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Program type")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_PI)
    .name("Program ID")
    .title("Program ID:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Program ID")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_RADIOTEXT)
    .name("Radio text")
    .title("Radio Text:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Radio text")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_CLOCKTIME)
    .name("Clock time")
    .title("Clock Time:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Clock time")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_ALTFREQ)
    .name("Alt Frequencies")
    .title("Alt. Frequencies:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Alternative frequencies list")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
c_def()
    .idx(C_RDS_FLAGS)
    .name("Flags")
    .title("Flags:")
    .title_placement(c_def::grid_placement(PLACE_NEXT,0))
    .placement(c_def::grid_placement(PLACE_SAME,PLACE_NEXT))
    .hint("RDS Flags")
    .g_type(G_LABEL)
    .dock(D_RDS)
    .scope(S_VFO)
    .v_type(V_STRING)
    .def("")
    .min("")
    .max("")
    .step("")
    .readable(true)
    .writable(false)
    .event(true)
    ,
};

std::array<std::function<void (const int, const c_def::v_union &)>, C_COUNT> conf_base::observers{};

bool c_def::clip(c_def::v_union & v) const
{
    if(v_type()==V_STRING)
        return false;
    if(v>d_max)
    {
        v=d_max;
        return true;
    }
    if(v<d_min)
    {
        v=d_min;
        return true;
    }
    return false;
}

const std::array<c_def,C_COUNT> & c_def::all()
{
    return store;
}

bool conf_base::register_observer(c_id optid, std::function<void (const int, const c_def::v_union &)> pevent)
{
    observers[optid]=pevent;
    return true;
}

const std::function<void (const int, const c_def::v_union &)> & conf_base::observer(c_id id) const
{
    return observers[id];
}

void conf_base::changed_value(c_id id, const int rx, const c_def::v_union & value) const
{
    auto & handler = observer(id);
    if(handler)
        handler(rx, value);
}
