find_package(PkgConfig)
PKG_CHECK_MODULES(PC_RNNOISE "rnnoise")

FIND_PATH(RNNOISE_INCLUDE_DIRS
    NAMES rnnoise.h
    HINTS ${PC_RNNOISE_INCLUDE_DIR}
    ${CMAKE_INSTALL_PREFIX}/include
    PATHS
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(RNNOISE_LIBRARIES
    NAMES rnnoise ${RNNOISE_LIBRARY_NAME}
    HINTS ${PC_RNNOISE_LIBDIR}
    ${CMAKE_INSTALL_PREFIX}/lib
    ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS
    ${RNNOISE_INCLUDE_DIRS}/../lib
    /usr/local/lib
    /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RNNOISE DEFAULT_MSG RNNOISE_LIBRARIES RNNOISE_INCLUDE_DIRS)
MARK_AS_ADVANCED(RNNOISE_LIBRARIES RNNOISE_INCLUDE_DIRS)

if (RNNOISE_FOUND AND NOT TARGET rnnoise::rnnoise)
  add_library(rnnoise::rnnoise INTERFACE IMPORTED)
  set_target_properties(rnnoise::rnnoise PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${RNNOISE_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${RNNOISE_LIBRARIES}"
  )
endif()
